server:
  port: 8301

spring:
  application:
    name: consumer-demo
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    #切换成nacos

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/